### ISSUE TITLE
USER STORY: Set up and install Django

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#14]
As a developer, I can set up django and the necessary software packages, so that I can deploy the site and begin development

## Tasks
- [x] Create Github repository using the CI template
- [x] Create Gitpod workspace
- [x] install psycopg2
- [x] install gunicorn
- [x] Create requirements.txt file
