### ISSUE TITLE
USER STORY: Set up secure environment variables for Django

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#15]
As a **developer**, I want **to set up the Django secret key and database variables in the env.py file**, so that **they are kept secure during deployment and not accidentally exposed**

## Tasks
- [x] Create env.py file to store variables
- [x] Add to django settings file
- [x] Add env.py to gitignore so it is not committed
- [x] Add hidden variables to heroku environment once deployed
