### ISSUE TITLE
USER STORY: Deploy early to Heroku

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#16]
As a **developer**, I want **deploy the site to Heroku soon after installation**, so that **I can ensure that the development pipeline is functioning and I can work on the main features of the site**

## Tasks
- [x] Log into the Heroku dashboard and create a new app
- [x] Add a postgres database
- [x] Configure the database section of the settings.py file to point to point to the correct location for local and deployed instances
