### ISSUE TITLE
USER STORY: Create User Profile

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#17]
As a **user**, I can **create a profile on the site**, so that **I can save my personal details such as addresses, use the wishlist and commenting features, and view past orders**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a new user without an account
	**When** I visit the homepage
	**Then** I can click the account button and see a link to register a new profile
- Acceptance Criteria 2
	**Given** that I clicked on the register button
	**When** I enter my details such as name and email address
	**Then** my account is created and I am automatically signed in
- Acceptance Criteria 3
	**Given** that I am a registered user
	**When** I visit the homepage
	**Then** the menu changes to no longer show a register button

## Tasks
- [x] create user model
- [x] add link to navbar menu to allow new users to register account
- [x] add form for user registration
- [x] hide this link for logged in users
