### ISSUE TITLE
USER STORY: Email Login instead of Username

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#18]
As a **user**, I can **register and use an account with just my email address**, so that **I don't have to remember and manage a username as well**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I register for an account on the site
	**When** I input my details on the registration form
	**Then** I only need to use my email address to register 

## Tasks
- [x] Create custom user model using AbstractUser class
- [x] update settings.py
- [x] Register new class with admin.py
- [x] update registration forms
