### ISSUE TITLE
USER STORY: Update User Profile 

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#20]
As a **user**, I can **view my own profile page**, so that **I can edit my own personal details such as email address and shipping or billing address**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am logged into the site and viewing my profile page
	**When** I see my email address displayed
	**Then** I can see a link to update my email address
- Acceptance Criteria 2
	**Given** that I am viewing my profile page
	**When** I see my personal addresses
	**Then** I can edit the details of these addresses
- Acceptance Criteria 3
	**Given** that I am not logged in to the site
	**When** I attempt to view my user profile
	**Then** I am redirected to the login page

## Tasks
- [x] display the user email and address details on the profile page
- [x] add edit buttons beside these
- [x] add views and forms to update these changes in the database
- [x] require a login for these pages to make sure no one else can edit or view profiles other than their own
