### ISSUE TITLE
USER STORY: Delete User Profile

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#21]
As a **user**, I can **delete my profile from the site**, so that ** I can remove or protect my personal information**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am registered on the site and logged in to my account
	**When** I click on my profile page link
	**Then** I can see a button allowing me to delete my account
- Acceptance Criteria 2
	**Given** that I click the button to delete my profile
	**When** a confirmation dialog is shown
	**Then** I can confirm or reject the option to delete my account
- Acceptance Criteria 3
	**Given** that I confirmed my desire to delete the account
	**When** the account is successfully deleted
	**Then** I am logged out and returned to the home page

## Tasks
- [x] add a button to the user profile page allowing the user to request to delete their account
- [x] add a form which ensures confirmation of this desire
- [x] after deletion return the user to the home page
- [x] authenticate this request to ensure it comes from a logged in user who owns the account
