### ISSUE TITLE
USER STORY: Store Multiple Addresses

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#22]
As a **user**, I can **store multiple addresses on the site**, so that **I can select my desired shipping or billing address at the time of checkout**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am checking out my cart on the site
	**When** the checkout form appears
	**Then** I have the option to select from a a number of saved addresses 
- Acceptance Criteria 2
	**Given** that I am viewing my profile page
	**When** I access the addresses section
	**Then** I have the option to add and store multiple addresses

## Tasks
- [ ] Create model for addresses
- [ ] add views and forms to carry out CRUD operations for addresses
- [ ] add links to user profile page and checkout page to access these operations

**Comment by neil314159** [comment]
Decided to stick with one address per user for now
