### ISSUE TITLE
USER STORY: Set up S3 Storage

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#23]
As a **developer**, I can **store my static images and files in the cloud**, so that **they can be quickly accesses and served to website users**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I upload a file or image to the website
	**When** file is uploaded
	**Then** it is stored in secure cloud storage

## Tasks
- [x] Adjust static storage settings on Django to use S3
- [x] Create S3 bucket on AWS
- [x] Add S3 variables to heroku deployment

**Comment by neil314159** [comment]
S3 storage was switched to Cloudinary after there was an issue with my credit card being rejected by AWS
