### ISSUE TITLE
USER STORY: Authenticate User Login/Logout

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#24]
As a **user**, I can **log and and log out of the site**, so that **my personal information is secure**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am not logged in to the site
	**When** I click the login button
	**Then** I can enter my personal login details and log into the site with the correct name and password
- Acceptance Criteria 2
	**Given** that I am logged in to the site as a user
	**When** I click the logout button
	**Then** my account is fully signed out and I am redirected to the home page

## Tasks
- [x] install and configure allauth software
- [x] create a login form template 
- [x] validate the user inputs for the form
- [x] reflect logged in/out state in navbar buttons
