### ISSUE TITLE
USER STORY: Social Media Login

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#25]
As a **user**, I can **use my social accounts such as Twitter or Facebook or Google to sign in**, so that **I can consolidate my accounts and avoid creating new passwords**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I select the register account button on the navbar
	**When** I see the registration form
	**Then** I am given the option to sign in with alternative account providers such as Google or Twitter
- Acceptance Criteria 2
	**Given** that I have logged in with my social account
	**When** the login process is complete
	**Then** I am redirected to the homepage

## Tasks
- [ ] Configure allauth software package for social login
- [ ] create developer accounts and API keys for these providers
- [ ] ensure that social logins work the same as normally registered users
