### ISSUE TITLE
USER STORY: Reset User Password 

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#26]
As a **user**, I can **reset my password**, so that **can regain access my account if my password is lost or forgotten**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I attempt to log in to the site with my credentials
	**When** I enter a wrong password
	**Then** I can select a link to reset my password
- Acceptance Criteria 2
	**Given** that I click on the link to reset my password
	**When** I confirm my email address
	**Then** I am sent a link to my email address to allow resetting the password
- Acceptance Criteria 3
	**Given** I have clicked this link and successfully reset my password
	**When** I attempt to log in
	**Then** my new password should work properly

## Tasks
- [x] Install allauth and configure
- [x] ensure email addresses are validated for users
- [x] add SMTP credentials for mail sending
- [x] add template for resetting password
