### ISSUE TITLE
USER STORY: View Store Items

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#28]
As a **user**, I can **view all items for sale**, so that **I can choose the items I want and add them to my cart**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I have clicked the link to view the shop
	**When** I open the shop page
	**Then** I can view a list of all items for sale in the shop
- Acceptance Criteria 2
	**Given** that I have selected a category of product
	**When** items are displayed 
	**Then** only items from the selected category are shown 
- Acceptance Criteria 3
	**Given** that I select a method of ranking the items such as price, alphabetically
	**When** items are presented to me
	**Then** they are in the correct order

## Tasks
- [x] add template for shop page
- [x] add category menu links to the main navbar
- [x] add search filter to only return products from the selected category
- [x] add drop down menu to rank products by name, price etc
- [x] create bootstrap card displays for product page
