### ISSUE TITLE
USER STORY: View Product Details

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#29]
As a **user**, I can **click on the thumbnail of a product**, so that **I can see in-depth information on the product and add it to my cart**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am viewing a list of products for sale on the site
	**When** I click on the thumbnail of a particular product
	**Then** I can see a new page with in-depth details of the product
- Acceptance Criteria 2
	**Given** that I am viewing the Product page
	**When** product details are presented to me
	**Then** I can select size, quantity options before adding to the shopping cart

## Tasks
- [x] create template for product display page
- [x] link to product model
- [x] ensure image and description are clearly visible
