### ISSUE TITLE
USER STORY: Edit Products

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#30]
As a **site owner**, I can **edit the details of any product on the site**, so that **product information can be updated or corrected when necessary**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am in administrator on the site
	**When** I login to the site
	**Then** I can see edit buttons on the product pages
- Acceptance Criteria 2
	**Given** I have clicked the product edit button
	**Then** I am presented with a form to make these edits
- Acceptance Criteria 3
	**Given** that I have adjusted the details of the product
	**When** the form is submitted
	**Then** the new details appear on product listing

## Tasks
- [x] add edit button to product template
- [x] link edit form to this button
- [x] restrict editing access to administrator users
