### ISSUE TITLE
USER STORY: Delete Products

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#31]
As a **site owner**, I can **delete products from the site**, so that **old products can be removed**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a site administrator
	**When** I view a product page
	**Then** there is a delete button available
- Acceptance Criteria 2
	**Given** I have clicked the delete product button
	**When** the dialogue prompt is confirmed
	**Then** the product was deleted

## Tasks
- [x] add delete button to product template
- [x] restrict to logged in admin users
- [x] possibly set boolean flag rather than removing product outright so the operation could be reversed if necessary
