### ISSUE TITLE
USER STORY: Add New Product

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#32]
As a **site owner**, I can **add products to the site**, so that **new items are made available for sale to customers**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a logged in administrator on the site
	**When** I view the navbar menu
	**Then** there is a link to add a new product
- Acceptance Criteria 2
	**Given** I have clicked the link to add new product
	**Then** I am presented with a form to enter the product details
- Acceptance Criteria 3
	**Given** I have entered these details and uploaded any required images 
	**When** the submit button is clicked 
	**Then**the new product is created and appears on the site

## Tasks
- [x] add form for new product creation
- [x] check that image upload is working with S3
- [x] display message confirming the product is successfully added
- [x] restrict action to logged in admin users
