### ISSUE TITLE
USER STORY: Search Functionality

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#33]
As a **user**, I can **search for products on the site**, so that **find the products I wish to purchase**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a user on the site
	**When** I examine the navbar menu
	**Then** I can access a search box
- Acceptance Criteria 2
	**Given** that I have entered a term into the search box
	**When** the button is clicked or I hit return
	**Then** a list of products matching my query is displayed 

## Tasks
- [x] add search box to navbar
- [x] link to search query
- [x] create template for search results
- [x] add live search update on keypress
