### ISSUE TITLE
USER STORY: Add Product to Cart

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#34]
As a **user**, I can **add products from the store to my shopping cart**, so that **I can purchase them later**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am browsing the site as a registered or unregistered user
	**When** I click the add to cart button on a product I wish to purchase
	**Then** the product is added to my shopping cart
- Acceptance Criteria 2
	**Given** I am a customer on the site
	**When** I add a product for the second time
	**Then** The shopping cart updates to increase the quantity of the item

## Tasks
- [x] Add shopping cart template
- [x] Add shopping cart links to navbar
- [x] Adjust shopping cart icon to reflect purchases added
