### ISSUE TITLE
USER STORY: Edit/Remove Shopping Cart Items 

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#35]
As a **user**, I can **update the quantity of, or remove items from the shopping cart**, so that **I can purchase the products I wish in the correct quantity**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am viewing my shopping cart
	**When** I click to adjust the quantity of items in the cart
	**Then** the cart updates to reflect these changes
- Acceptance Criteria 2
	**Given** that I click delete on an item in the shopping cart
	**Then** the item is removed from the cart
- Acceptance Criteria 3
	**Given** that an item has been removed from the cart
	**When** item is gone an undo link appears in its place
	**Then** it is possible to undo the removal of the item

## Tasks
- [x] add links to shopping cart page to update or remove items
- [ ] use HTMX to reflect changes in navbar totals right away
- [ ] add link to undo removal of shopping cart item in case user changes mind

**Comment by neil314159** [comment]
Shopping cart is functional, decided to avoid HTMX integration due to some slight bugs found in testing
