### ISSUE TITLE
USER STORY: Checkout Page 

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#37]
As a **user**, I can **use the checkout page to pay for my purchases**, so that **I can receive the products**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am user on the site
	**When** I am on the shopping cart page
	**Then** I can click to proceed to the checkout

## Tasks
- [x] add link to checkout to shopping cart page
- [x] add stripe API keys to Django and heroku
- [x] add web hook handler code
- [x] create payment intent in checkout view
