### ISSUE TITLE
USER STORY: View Order Details

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#38]
As a **user**, I can **view the details of my order**, so that **I can see that my order has been processed successfuly**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I have entered my payment details and clicked Order
	**When** the payments has completed
	**Then** I can see the details of my order
- Acceptance Criteria 2
	**Given** that I am user on the site
	**When** the order has been successfully processed
	**Then** the order will appear on my profile page and I will receive a confirmation email

## Tasks
- [x] create template for order details page
- [x] link order to user model to appear on profile page
- [x] check SMTP settings and generate order success email

**Comment by neil314159** [comment]
order details working, will tackle email issue separately
