### ISSUE TITLE
USER STORY: PDF Receipt 

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#39]
As a **user**, I can **download a PDF receipt for my order**, so that **I can save it for future reference**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a user on the site
	**When** I view the order confirmation page
	**Then** I can see a link to download a PDF receipt of my order
- Acceptance Criteria 2
	**Given** that I have placed a successful order
	**Then** I will receive a copy of my PDF receipt in my email confirmation 

## Tasks
- [ ] install PDF generation library
- [ ] create Pdf generation template
- [ ] add to order page and success email

**Comment by neil314159** [comment]
Closing issue due to large number of dependencies required for PDF generation which was causing errors during testing. Closing for now but could revisit with a better library/API
