### ISSUE TITLE
USER STORY: Calculate Product Ratings

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#42]
As a **user**, I can **see the average score of all reviews left on a product**, so that **make an informed decision about my purchase **

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a user on the site
	**When** I leave a review with a star rating
	**Then** this rating is added to the product database
- Acceptance Criteria 2
	**Given** that I am user browsing the site
	**When** the product thumbnails are presented to me
	**Then** the review scores of each product are shown in the product details 

## Tasks
- [x] add star rating to review form
- [x] average all star ratings for each product 
- [x] add to product details page and allow products to be ranked by review score
