### ISSUE TITLE
USER STORY: Read Blog

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#43]
As a **user**, I can **read the blog section of the site**, so that **learn and understand more about the products for sale on the site**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am customer on the site
	**When** I click the blog button in the navbar
	**Then** I can access the blog section of the site
- Acceptance Criteria 2
	**Given** that I have clicked the blog button in the navbar
	**Then** I will see a dropdown menu offering a choice of blog categories to browse 
- Acceptance Criteria 3 
	**Given** that I am a user browsing the blog
	**When** I click on the article thumbnail 
	**Then** I can read the individual blog post

## Tasks
- [x] create blog app and models
- [x] create dynamic navbar menu to reflect categories 
- [x] create blog template

**Comment by neil314159** [comment]
navbar template updated with dynamic loading categories
