### ISSUE TITLE
USER STORY: Add, Edit and Delete Blog Categories

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#45]
As a **site owner**, I can **add, edit and remove blog categories**, so that **blog posts are correctly categorised and easily accessed**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a logged in admin user
	**When** I am viewing the blog admin page
	**Then** I can see buttons allowing me to add, edit and remove categories for the blog
- Acceptance Criteria 2
	**Given** that I have selected to add a new category 
	**Then** a new category is added to the form for creating a new blog post
- Acceptance Criteria 3
	**Given** that I am in the blog admin page
	**When** I select to edit or remove a blog category
	**Then** this action is reflected in the navbar menu and the new post form

## Tasks
- [x] add model for category
- [x] add HTMX form to update instantly CRUD operations
- [x] ensure updated categories appear in new post form
