### ISSUE TITLE
USER STORY: View Wishlist on Profile Page

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#47]
As a **user**, I can **click on the link to my profile page**, so that **I can see at a glance all the items stored in my wishlist**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a logged in user on the site
	**When** I click my profile page
	**Then** I can see a section detailing all my wishlist items 
- Acceptance Criteria 2
	**Given** that I am viewing my wishlist on the profile page
	**When** viewing the list
	**Then** I can see buttons to remove any item from the wishlist

## Tasks
- [x] add wishlist section to profile page
- [x] add button to remove from wishlist beside each item
- [x] add link to visit product page by clicking wishlist item title
