### ISSUE TITLE
USER STORY: Admin Dashboard 

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#48]
As a **site owner**, I can **view a dashboard outlining admin functions**, so that **I can save time and effectively manage the site**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a logged in admin user
	**When** I click the admin link in the navbar
	**Then** I am presented with an admin dahsboard for the site
- Acceptance Criteria 2
	**Given** that I am viewing the admin dashboard
	**Then** I can see shortcut buttons for adding, editing and removing blog posts or categories 
- Acceptance Criteria 3
	**Given** that I am viewing the admin dashboard
	**Then** I can see shortcut buttons for adding, editing and removing products
- Acceptance Criteria 4
	**Given** that I am viewing the admin dashboard
	**Then** I can see a list overview of all products and blog posts on the site

## Tasks
- [x] create dashboard template
- [x] add shortcut buttons for CRUD functions
- [x] create list views of all product and blog posts for easy access
