### ISSUE TITLE
USER STORY: Printable Shipping Labels

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#51]
As a **site owner**, I can **print a list of shipping labels for all unshipped orders**, so that **customers can receive their orders quickly**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a logged in admin user
	**When** viewing the admin dashboard
	**Then** I can click a link to generate a PDF download with the shipping details of all open orders

## Tasks
- [x] create list of open orders
- [ ] compile into PDF template
- [ ] offer as download on admin page

**Comment by neil314159** [comment]
This proved difficult for the same reason that the PDF receipts did not work, it was easy to extract a list of addresses for unshipped orders, but the dependencies needed to generate PDFS worked locally but not always on Heroku.
