### ISSUE TITLE
USER STORY: Site Requirements 

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#52]
As a **site owner**, I can **ensure that all necessary pages are added to the e-commerce site**, so that **customers can benefit from the full functionality of the site**

## Tasks
- [x] add 404 page
- [x] add sitemap
- [x] add robots.txt
- [x] add newsletter signup
- [x] add privacy policy
- [x] add footer with links to these
- [x] add bootstrap theme
- [x] pick appropriate typography and colour scheme
