### ISSUE TITLE
USER STORY: Keyword Research and SEO

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#54]
As a **site owner**, I can **research relevant keywords for my site**, so that **I can carry out effective SEO and social media marketing**

## Tasks
- [x] research relevant keywords using marketing tools
- [x] add keywords to meta tags
- [x] compile keyword list for use in social media posts
- [x] ensure all templates have semantic markup and tagging
