### ISSUE TITLE
USER STORY: Social Media Marketing

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#55]
As a **site owner**, I can **create pages on major social media outlets**, so that **customers can learn about the store and products offered for sale**

## Tasks
- [x] create Facebook page
- [x] create twitter account
- [x] create instagram page
- [x] add 5 posts to each account
- [x] create content for site blog and share links on social media
