### ISSUE TITLE
USER STORY: User Testing

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#57]
As a **developer**, I can **ask a person who has never used the site before to test it while I watch**, so that **I can gather feedback about the usability and functionality of the site **

## Tasks
- [x] find a person who has never used the site 
- [x] ask them to register an account and make purchases while I watch how they interact with the site
- [x] incorporate any feedback provided

**Comment by neil314159** [comment]
After asking someone to use the site and observing their behaviour and feedback, I have made a number of notes about visual changes and improving the clarity of the homepage.
