### ISSUE TITLE
USER STORY: Manual Testing 

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#58]
As a **developer**, I can **develop a plan to manually test every aspect of the site's functionality**, so that **users can have a bug-free experience**

## Tasks
- [x] create a spreadsheet outlining every area of the site and a list of steps to manually test each one
- [x] record the results of the tests 
- [x] compile a list of bugs to be fixed
- [x] write up the testing strategy in the Readme file
