### ISSUE TITLE
USER STORY: Automated Testing

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#59]
As a **developer**, I can **create a set of automated unit tests**, so that **I can reduce the number of bugs present on the site**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that each major function is covered by a test case
	**When** the test suite is run
	**Then** the code should be free of errors

## Tasks
- [ ] create unit tests for each main function
- [ ] run auto validation on Python, HTML and CSS code
- [ ] generate coverage report

**Comment by neil314159** [comment]
focussed on manual testing strategy instead, also using HTMX library made it more difficult to mock up requests properly
