### ISSUE TITLE
USER STORY: Coupon Code

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#60]
As a **user**, I can **enter a coupon code at the checkout**, so that **I can receive a discount on my order**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a user at the checkout page
	**When** I enter a coupon code in the provided box
	**Then** the total of my shopping cart amount is reduced my the amount of the coupon
- Acceptance Criteria 2
	**Given** that I am an admin user on the site 
	**When** I log in to the admin dashboard
	**Then** I have the option to add, edit or delete coupon codes

## Tasks
- [ ] add coupon field to checkout
- [ ] create coupon model and CRUD functions
- [ ] add to admin dashboard
- [ ] adjust shopping cart calculations to account for coupon

**Comment by neil314159** [comment]
Left for future development
