### ISSUE TITLE
USER STORY: Purchase Recommendations

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-5#61]
As a **user on the site**, I can **view items that other customers also purchased when viewing a product page**, so that **I can be advised abut products that go well together and I might like to purchase**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a customer on the site
	**When** I view a product detail page
	**Then** I can see a short list of other products that other customers have purchased at the same time as the product I am looking at
- Acceptance Criteria 2
	**Given** that I am viewing this shortlist of recommended purchases
	**When** I click the thumbnail of one of the recommendations
	**Then** I am taken to the product page where I can add it to my cart

## Tasks
- [x] create database model linking purchases with items bought together
- [ ] create counter to measure number of times this has happened
- [ ] add to the product detail page template a list of recommended products

**Comment by neil314159** [comment]
Closed to due to lack of time to develop, needs better database model to relate purchases to each other
